/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTrustRouteImport } from './routes/admin/trust'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServiceCertificateRouteImport } from './routes/admin/service-certificate'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminPromotionTermsRouteImport } from './routes/admin/promotion-terms'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPrivilegesRouteImport } from './routes/admin/privileges'
import { Route as AdminPrivacyPolicyRouteImport } from './routes/admin/privacy-policy'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMomentsRouteImport } from './routes/admin/moments'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLeadFormRouteImport } from './routes/admin/lead-form'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminBonusesRouteImport } from './routes/admin/bonuses'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrustRoute = AdminTrustRouteImport.update({
  id: '/admin/trust',
  path: '/admin/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceCertificateRoute = AdminServiceCertificateRouteImport.update({
  id: '/admin/service-certificate',
  path: '/admin/service-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionTermsRoute = AdminPromotionTermsRouteImport.update({
  id: '/admin/promotion-terms',
  path: '/admin/promotion-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrivilegesRoute = AdminPrivilegesRouteImport.update({
  id: '/admin/privileges',
  path: '/admin/privileges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrivacyPolicyRoute = AdminPrivacyPolicyRouteImport.update({
  id: '/admin/privacy-policy',
  path: '/admin/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMomentsRoute = AdminMomentsRouteImport.update({
  id: '/admin/moments',
  path: '/admin/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadFormRoute = AdminLeadFormRouteImport.update({
  id: '/admin/lead-form',
  path: '/admin/lead-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBonusesRoute = AdminBonusesRouteImport.update({
  id: '/admin/bonuses',
  path: '/admin/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bonuses': typeof AdminBonusesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lead-form': typeof AdminLeadFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/privacy-policy': typeof AdminPrivacyPolicyRoute
  '/admin/privileges': typeof AdminPrivilegesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotion-terms': typeof AdminPromotionTermsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-certificate': typeof AdminServiceCertificateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bonuses': typeof AdminBonusesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lead-form': typeof AdminLeadFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/privacy-policy': typeof AdminPrivacyPolicyRoute
  '/admin/privileges': typeof AdminPrivilegesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotion-terms': typeof AdminPromotionTermsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-certificate': typeof AdminServiceCertificateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/bonuses': typeof AdminBonusesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lead-form': typeof AdminLeadFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/privacy-policy': typeof AdminPrivacyPolicyRoute
  '/admin/privileges': typeof AdminPrivilegesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promotion-terms': typeof AdminPromotionTermsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-certificate': typeof AdminServiceCertificateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/bonuses'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/lead-form'
    | '/admin/login'
    | '/admin/media'
    | '/admin/moments'
    | '/admin/notifications'
    | '/admin/privacy-policy'
    | '/admin/privileges'
    | '/admin/profile'
    | '/admin/promotion-terms'
    | '/admin/seo'
    | '/admin/service-certificate'
    | '/admin/settings'
    | '/admin/trust'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/bonuses'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/lead-form'
    | '/admin/login'
    | '/admin/media'
    | '/admin/moments'
    | '/admin/notifications'
    | '/admin/privacy-policy'
    | '/admin/privileges'
    | '/admin/profile'
    | '/admin/promotion-terms'
    | '/admin/seo'
    | '/admin/service-certificate'
    | '/admin/settings'
    | '/admin/trust'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/bonuses'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/lead-form'
    | '/admin/login'
    | '/admin/media'
    | '/admin/moments'
    | '/admin/notifications'
    | '/admin/privacy-policy'
    | '/admin/privileges'
    | '/admin/profile'
    | '/admin/promotion-terms'
    | '/admin/seo'
    | '/admin/service-certificate'
    | '/admin/settings'
    | '/admin/trust'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminBonusesRoute: typeof AdminBonusesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLeadFormRoute: typeof AdminLeadFormRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMomentsRoute: typeof AdminMomentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPrivacyPolicyRoute: typeof AdminPrivacyPolicyRoute
  AdminPrivilegesRoute: typeof AdminPrivilegesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPromotionTermsRoute: typeof AdminPromotionTermsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServiceCertificateRoute: typeof AdminServiceCertificateRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrustRoute: typeof AdminTrustRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trust': {
      id: '/admin/trust'
      path: '/admin/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AdminTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-certificate': {
      id: '/admin/service-certificate'
      path: '/admin/service-certificate'
      fullPath: '/admin/service-certificate'
      preLoaderRoute: typeof AdminServiceCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotion-terms': {
      id: '/admin/promotion-terms'
      path: '/admin/promotion-terms'
      fullPath: '/admin/promotion-terms'
      preLoaderRoute: typeof AdminPromotionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/privileges': {
      id: '/admin/privileges'
      path: '/admin/privileges'
      fullPath: '/admin/privileges'
      preLoaderRoute: typeof AdminPrivilegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/privacy-policy': {
      id: '/admin/privacy-policy'
      path: '/admin/privacy-policy'
      fullPath: '/admin/privacy-policy'
      preLoaderRoute: typeof AdminPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moments': {
      id: '/admin/moments'
      path: '/admin/moments'
      fullPath: '/admin/moments'
      preLoaderRoute: typeof AdminMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-form': {
      id: '/admin/lead-form'
      path: '/admin/lead-form'
      fullPath: '/admin/lead-form'
      preLoaderRoute: typeof AdminLeadFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bonuses': {
      id: '/admin/bonuses'
      path: '/admin/bonuses'
      fullPath: '/admin/bonuses'
      preLoaderRoute: typeof AdminBonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminBonusesRoute: AdminBonusesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLeadFormRoute: AdminLeadFormRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMomentsRoute: AdminMomentsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPrivacyPolicyRoute: AdminPrivacyPolicyRoute,
  AdminPrivilegesRoute: AdminPrivilegesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPromotionTermsRoute: AdminPromotionTermsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServiceCertificateRoute: AdminServiceCertificateRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrustRoute: AdminTrustRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
