/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminItemsIndexRouteImport } from './routes/api/admin/items.index'
import { Route as ApiAdminContentIndexRouteImport } from './routes/api/admin/content.index'
import { Route as ApiPublicUploadsFilenameRouteImport } from './routes/api/public/uploads.$filename'
import { Route as ApiAdminItemsIdRouteImport } from './routes/api/admin/items.$id'
import { Route as ApiAdminContentIdRouteImport } from './routes/api/admin/content.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminItemsIndexRoute = ApiAdminItemsIndexRouteImport.update({
  id: '/api/admin/items/',
  path: '/api/admin/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentIndexRoute = ApiAdminContentIndexRouteImport.update({
  id: '/api/admin/content/',
  path: '/api/admin/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadsFilenameRoute =
  ApiPublicUploadsFilenameRouteImport.update({
    id: '/api/public/uploads/$filename',
    path: '/api/public/uploads/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminItemsIdRoute = ApiAdminItemsIdRouteImport.update({
  id: '/api/admin/items/$id',
  path: '/api/admin/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentIdRoute = ApiAdminContentIdRouteImport.update({
  id: '/api/admin/content/$id',
  path: '/api/admin/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/content/$id': typeof ApiAdminContentIdRoute
  '/api/admin/items/$id': typeof ApiAdminItemsIdRoute
  '/api/public/uploads/$filename': typeof ApiPublicUploadsFilenameRoute
  '/api/admin/content/': typeof ApiAdminContentIndexRoute
  '/api/admin/items/': typeof ApiAdminItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/content/$id': typeof ApiAdminContentIdRoute
  '/api/admin/items/$id': typeof ApiAdminItemsIdRoute
  '/api/public/uploads/$filename': typeof ApiPublicUploadsFilenameRoute
  '/api/admin/content': typeof ApiAdminContentIndexRoute
  '/api/admin/items': typeof ApiAdminItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/content/$id': typeof ApiAdminContentIdRoute
  '/api/admin/items/$id': typeof ApiAdminItemsIdRoute
  '/api/public/uploads/$filename': typeof ApiPublicUploadsFilenameRoute
  '/api/admin/content/': typeof ApiAdminContentIndexRoute
  '/api/admin/items/': typeof ApiAdminItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/media'
    | '/api/admin/content/$id'
    | '/api/admin/items/$id'
    | '/api/public/uploads/$filename'
    | '/api/admin/content/'
    | '/api/admin/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/admin'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/media'
    | '/api/admin/content/$id'
    | '/api/admin/items/$id'
    | '/api/public/uploads/$filename'
    | '/api/admin/content'
    | '/api/admin/items'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/media'
    | '/api/admin/content/$id'
    | '/api/admin/items/$id'
    | '/api/public/uploads/$filename'
    | '/api/admin/content/'
    | '/api/admin/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminContentIdRoute: typeof ApiAdminContentIdRoute
  ApiAdminItemsIdRoute: typeof ApiAdminItemsIdRoute
  ApiPublicUploadsFilenameRoute: typeof ApiPublicUploadsFilenameRoute
  ApiAdminContentIndexRoute: typeof ApiAdminContentIndexRoute
  ApiAdminItemsIndexRoute: typeof ApiAdminItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/items/': {
      id: '/api/admin/items/'
      path: '/api/admin/items'
      fullPath: '/api/admin/items/'
      preLoaderRoute: typeof ApiAdminItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/': {
      id: '/api/admin/content/'
      path: '/api/admin/content'
      fullPath: '/api/admin/content/'
      preLoaderRoute: typeof ApiAdminContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uploads/$filename': {
      id: '/api/public/uploads/$filename'
      path: '/api/public/uploads/$filename'
      fullPath: '/api/public/uploads/$filename'
      preLoaderRoute: typeof ApiPublicUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/items/$id': {
      id: '/api/admin/items/$id'
      path: '/api/admin/items/$id'
      fullPath: '/api/admin/items/$id'
      preLoaderRoute: typeof ApiAdminItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/$id': {
      id: '/api/admin/content/$id'
      path: '/api/admin/content/$id'
      fullPath: '/api/admin/content/$id'
      preLoaderRoute: typeof ApiAdminContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminContentIdRoute: ApiAdminContentIdRoute,
  ApiAdminItemsIdRoute: ApiAdminItemsIdRoute,
  ApiPublicUploadsFilenameRoute: ApiPublicUploadsFilenameRoute,
  ApiAdminContentIndexRoute: ApiAdminContentIndexRoute,
  ApiAdminItemsIndexRoute: ApiAdminItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
